name: Generate Snake Animation

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Pull down the Snake animation script
      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: nidulaNemsith
          svg_out_path: dist/output/github-contribution-grid-snake.svg

      # Push the animation to the GitHub repository
      - name: Push generated Snake
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/output
