name: Generate Snake Animation

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Generate the snake
      - name: Generate Snake animation
        uses: Platane/snk@v3  # Correct version
        with:
          github_user_name: nidulaNemsith  # Replace with your GitHub username
          outputs: dist/snake.svg

      # Upload the snake as an artifact
      - name: Upload Snake animation
        uses: actions/upload-artifact@v3
        with:
          name: snake-graph
          path: dist/snake.svg
